### ISSUE TITLE
Implement Identifiable Aborts (take 2)

### ISSUE THREAD

**Issue by real-or-random** [BlockstreamResearch/bip-frost-dkg#37]
Implement the idea from https://github.com/BlockstreamResearch/bip-frost-dkg/issues/9#issuecomment-2220091151, ideally in a PR so we can judge the complexity.

Steps:
 - [x] ~Coordinator should probably check the messages received as far as possible (https://github.com/BlockstreamResearch/bip-frost-dkg/issues/29) and raise `InvalidContributionExcpetion`~
 - [x] The actual implementation of the idea (#52, #75)
 - [x] Document exceptions properly (#52, #62, #65)
 - [x] Document `blame` functions (#72, #75)
 - [x] Change BIP text to explain IA (this needs to say that the coordinator is fully trusted for IA) (#71, #74)

**Comment by real-or-random** [comment]
One natural way to do this is to let each coordinator_step return additional blame data, separate for each participant.  This could be an easy way of making IA optional: Just skip computing and sending this data around.

Not sure if it's worth making IA optional, but at least the additional complexity over non-optional IA is tiny.

**Comment by real-or-random** [comment]
> One natural way to do this is to let each coordinator_step return additional blame data, separate for each participant. This could be an easy way of making IA optional: Just skip computing and sending this data around.

Having separate blame data also has the advantage that "main" CoordinatorMsg remains the same for everyone. That is, if you don't need IA, you can get away with the coordinator sending the exact same bytes to everyone (without wasting communication), which may be simpler.
